### PR TITLE
nrpe_commands as dict and list

### PR DESCRIPTION
**Pull request by patrickkirsch**
In the case of hierarchical design it is desirable to have overriding behaviour.

Signed-off-by: patrick.kirsch@olanis.de <patrick.kirsch@olanis.de>

### CODE REVIEW

**Comment by gravyboat** [comment]
Hmm, does anyone remember if the mapping value is going to cause issues with older releases of Jinja? I feel like we've run into this before...

**Comment by puneetk** [comment]
Its an issue in jinja < 2.6, but that's been out for a while.

**Comment by gravyboat** [comment]
*waits with baited breath for an issue 20 minutes from now.*

**Comment by puneetk** [comment]
oh boy

**Comment by babilen** [comment]
This breaks if `nrpe_commands` isn't defined.

**Pull request merged**
